apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario-app
spec:
  replicas: 1
template:
  metadata:
    labels:
      app: mario
spec:
  containers:
    - name: mario
image: pengbai/docker-supermario
ports:
  - containerPort: 8080
