apiVersion: v1
kind: Service
metadata:
  name: supermario
  labels:
    app: supermario
spec:
  ports:
  - port: 8060
    name: supermario
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: supermario
